### ISSUE TITLE
A question about Demo

### ISSUE THREAD

**Issue by cvenwu** [izuolan/zresume#2]
I execute a command as 'curl -sSL https://git.io/Resume | bash', it told me that 'curl: (7) Failed to connect to raw.githubusercontent.com port 443: Timed out'. I don't know how to solve it

**Comment by izuolan** [comment]
Github 被墙了吧, 我能打开.

**Comment by cvenwu** [comment]
`$ curl -sSL https://git.io/Resume | bash -s 2333
Port: 2333
24470f81049e3bc8a1b9e14d61caad6c3b8ca00dd7ee65f82022531a93156a9c
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Drive has not been shared.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
Done
`
What should i do?

**Comment by izuolan** [comment]
这是Linux的脚本，看起来是挂载数据卷时出了问题，脚本是Linux的路径格式。没考虑Windows的情况。

如果确实需要在Win下运行，也可以手动执行：

```
docker run -d --name resume -p 2333:80 --restart=always  zuolan/resume
```

数据卷根据需要挂上去～

**Comment by cvenwu** [comment]
Good, it can works now!
